### ISSUE TITLE
Network resiliency

### ISSUE THREAD

**Issue by nicolaiheuck** [peterhym21/H5.IntelliHouse2000App#18]
1. Configure retry policies with Polly for the generic repository.
2. User-friendly error messages if no internet access is available

**Comment by nicolaiheuck** [comment]
3. Configure retry policy for MQTT client

**Comment by Thoroughbreed** [comment]
App doesn't crash when no network is present, however when I re-enabled WiFi it still wouldn't update the log page and fetch from API

What are the policy for retries?

**Comment by Thoroughbreed** [comment]
The alarm buttons doesn't re-enable when network is present again
(iOS)

**Comment by Thoroughbreed** [comment]
Some small hiccups

*Sometimes* it works, other times there's a slight delay.

Closing issue.
