### ISSUE TITLE
View Climate not updating

### ISSUE THREAD

**Issue by peterhym21** [peterhym21/H5.IntelliHouse2000App#26]
the propertyes form Climate:
Temp and Humid

can not update on the Views after getting data for the API for some reason
even Egon can seem to find out what the problem is

there is a branch sepret to this issue:
https://github.com/peterhym21/H5.IntelliHouse2000App/tree/dev/climate-notworking

**Comment by Thoroughbreed** [comment]
Made the property of the object [ObservableProperty]
